# 텐서플로우

In [1]:
!pip install --user tensorflow==2.7.0

In [1]:
import tensorflow

In [2]:
tensorflow.__version__

'2.7.0'

In [1]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [2]:
model = Sequential()

In [3]:
model.add(Dense(units=1, activation='linear', input_dim=1))

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[-0.01890659]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [6]:
model.predict([[11], [12], [13]])

array([[-0.20797253],
       [-0.22687912],
       [-0.24578571]], dtype=float32)

## 회귀(보스턴 집값)

In [7]:
import pandas as pd
import numpy as np
import random 
import tensorflow as tf
print(tf.__version__)

2.7.0


In [9]:
from sklearn import datasets
boston = datasets. load_boston()
X_data =boston.data

In [10]:
y_data = boston.target

In [11]:
print(X_data.shape, y_data.shape)

(506, 13) (506,)


In [12]:
y_data[:3]

array([24. , 21.6, 34.7])

In [13]:
X_data[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [14]:
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [15]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [16]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

### 전처리

In [19]:
from sklearn.preprocessing import MinMaxScaler
min_max = MinMaxScaler()
X_data_min_max = min_max.fit_transform(X_data)
X_data_min_max[0]

array([0.        , 0.18      , 0.06781525, 0.        , 0.31481481,
       0.57750527, 0.64160659, 0.26920314, 0.        , 0.20801527,
       0.28723404, 1.        , 0.08967991])

### 딥러닝 모델 만들어서

In [20]:
model2 = Sequential()
model2.add(Dense(128, activation='relu', input_dim=13))
model2.add(Dense(64, activation='relu'))
model2.add(Dense(1, activation='linear'))

### 위에 쌓은 모델로 설정해주기

In [21]:
model2.compile(optimizer='adam', loss='mse', metrics=['mae'])
model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 128)               1792      
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 10,113
Trainable params: 10,113
Non-trainable params: 0
_________________________________________________________________


### 공부시키고

In [24]:
model2.fit(X_data_min_max[:400], y_data[:400], epochs=3, batch_size=50, verbose=2)

Epoch 1/3
8/8 - 0s - loss: 253.8784 - mae: 13.0391 - 7ms/epoch - 873us/step
Epoch 2/3
8/8 - 0s - loss: 176.2453 - mae: 10.3807 - 5ms/epoch - 623us/step
Epoch 3/3
8/8 - 0s - loss: 135.3228 - mae: 8.7555 - 5ms/epoch - 625us/step


### 정확도 계산

In [25]:
model2.evaluate(X_data_min_max[:400], y_data[:400])

13/13 [==============================] - 0s 665us/step - loss: 126.2991 - mae: 8.4160


[126.29914855957031, 8.415999412536621]

In [ ]:
### 예측